### ISSUE TITLE
Task can be cancelled on hibernate

### ISSUE THREAD

**Issue by haf** [haf/Http.fs#145]
One exception not caught:

```
System.Exception: Failed to get response ---> System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Hopac.Core.TaskToJobAwaiter`1.DoWork(Worker& wr)
   at Hopac.Core.Worker.RunOnThisThread(Scheduler sr, Work work)
   --- End of inner exception stack trace ---
   at HttpFs.Client.getResponseOrFail@953[a,b](FSharpChoice`2 _arg1)
   at Hopac.Core.ContMap`2.DoCont(Worker& wr, X x)
   at Hopac.Once`1.DoJob(Worker& wr, Cont`1 xK)
   at Hopac.Core.JobUsing`2.ContUsing.DoCont(Worker& wr, Y y)
   at Hopac.Core.JobUsing`2.ContUsing.DoCont(Worker& wr, Y y)
   at Hopac.Core.Worker.Run(Scheduler sr, Int32 me)
```

**Comment by haf** [comment]
@ivpadim Some guesses: set up mitmproxy, set it to very slow, then call https://discourse.mitmproxy.org/t/killing-tcp-connections/775 `flow.kill()`; alternatively, you could call Suave with a `Async.Sleep 1000` and directly cancelling the async token of the client.
