### ISSUE TITLE
Beginner question: How to correctly download large files

### ISSUE THREAD

**Issue by NicoVIII** [haf/Http.fs#153]
Hey everyone!
I worked recently with Http.fs to communicate with an API including Authentication and stuff and it works very good. The only thing I could not make work is downloading large files.

My code for that looks like this:
```
job {
  use! resp =
    (Request.createUrl method url, auth)
    // Add auth data
    |> function
        | (r, NoAuth) ->
            r
        | (r, Auth {accessToken = token}) ->
            Request.setHeader (Authorization ("Bearer " + token)) r
    // Add query parameters
    |> List.fold (fun request query -> Request.queryStringItem query.name query.value request) <| queries
    |> getResponse
  use fileStream = new FileStream(filepath, FileMode.Create)
  printfn "Size of download: %s" resp.headers.[ResponseHeader.ContentLength]
  do! resp.body.CopyToAsync fileStream |> Job.awaitUnitTask
  printfn "Download completed!"
  fileStream.Close ()
}
```

After a while of downloading it throws an exception like that:

```
Unhandled Exception: System.Exception: Exception raised by job ---> System.Exception: Failed to get response ---> System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Hopac.Core.TaskToJobAwaiter`1.DoWork(Worker& wr)
   at Hopac.Core.Worker.RunOnThisThread(Scheduler sr, Work work)
   --- End of inner exception stack trace ---
   at HttpFs.Client.getResponseOrFail@974[a,b](FSharpChoice`2 _arg1)
   at Hopac.Core.ContMap`2.DoCont(Worker& wr, X x)
   at Hopac.Once`1.DoJob(Worker& wr, Cont`1 xK)
   at Hopac.Core.JobUsing`2.ContUsing.DoCont(Worker& wr, Y y)
   at Hopac.Core.JobUsing`2.ContUsing.DoCont(Worker& wr, Y y)
   at Hopac.Core.Worker.Run(Scheduler sr, Int32 me)
   --- End of inner exception stack trace ---
   at Hopac.Scheduler.run[x](Scheduler sr, Job`1 xJ)
   at Andromeda.Core.FSharp.Games.downloadGame(AppData appData, InstallerInfo installer) in /home/nico/Dokumente/Projekte/Github/Andromeda-for-GOG/Andromeda.Core/Games.fs:line 90
   at Program.mainloop(Boolean start, AppData appData) in /home/nico/Dokumente/Projekte/Github/Andromeda-for-GOG/Andromeda.ConsoleApp/Program.fs:line 101
```

For me it looks like the task is cancelled because of a timeout but I couldn't figure out where the timeout happens and how to avoid it for large files.
Does someone know what I have to do here to avoid this error? I'm not familiar with Hopac and have not much experience with async programming, so I apologise, if this is a stupid question or this is the wrong place to ask that.

**Comment by haf** [comment]
You never get to downloading any body, because you don't even get the response headers:

https://github.com/haf/Http.fs/blob/6fa93c84693484fcc8d7ec34496057ddeda8a993/HttpFs/HttpFs.fs#L946 

https://github.com/haf/Http.fs/blob/6fa93c84693484fcc8d7ec34496057ddeda8a993/HttpFs/HttpFs.fs#L798

Something cancels the request; perhaps it just times out because you don't get any response. It's not about the file size, since you never get to your code that downloads your response body. I use almost identical code to yours, in my own usage code:

<img width="587" alt="screen shot 2018-08-06 at 12 02 27" src="https://user-images.githubusercontent.com/193115/43710697-a21bfd50-9970-11e8-8e21-da415cae4d86.png">

**Comment by NicoVIII** [comment]
Alright, thanks for your fast response!
I have an idea now what could be wrong.
